finished setting up utility scripts working with dynamodb

diff --git a/backend-flask/bin/db/setup b/backend-flask/bin/db/setup
--- a/backend-flask/bin/db/setup
+++ b/backend-flask/bin/db/setup
@@ -1,5 +1,5 @@
 #! /usr/bin/bash
--e #stop if it fails at any point
+set -e #stop if it fails at any point
 
 CYAN='\033[1;36m'
 NO_COLOR='\033[0m'
@@ -9,11 +9,11 @@ bin_path="$(realpath .)/bin"
 
 if [ "$1" = "prod" ]; then
     printf "${CYAN}----- PRODUCTION MODE -----${NO_COLOR}\n"
-    source "$bin_path/db-schema-load" prod
-    source "$bin_path/db-seed" prod
+    source "$bin_path/db/schema-load" prod
+    source "$bin_path/db/seed" prod
 else
-    source "$bin_path/db-drop"
-    source "$bin_path/db-create"
-    source "$bin_path/db-schema-load"
-    source "$bin_path/db-seed"
+    source "$bin_path/db/drop"
+    source "$bin_path/db/create"
+    source "$bin_path/db/schema-load"
+    source "$bin_path/db/seed"
 fi
